version: "3"

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./www/html:/var/www/html
    depends_on:
      - php

  php:
    build: ./php
    volumes:
      - ./www/html:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:latest
    platform: linux/x86_64
    container_name: app_db
    ports:
      - 3305:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/sql:/docker-entrypoint-initdb.d
      - ./mysql/my.conf:/etc/mysql/conf.d
    environment:
      - MYSQL_DATABASE=posse
      - MYSQL_ROOT_PASSWORD=9999

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 8888:80
    depends_on:
      - db

#dockerの柱は、イメージとコンテナ
#アプリコードとdockerfileがイメージの雛形、そのイメージからコンテナを作成
#httpリクエストを受け取って、返してあげるアプリケーションのことをwebサーバーという
#アプリコード、ライブラリ、ベースイメージをまとめてdockerfileという。それをもとにイメージを作成
#
#